services:
  main-server:
    image: cskulab/main-server:sha-e45a921
    ports:
      - "8080:8080"
    environment:
      - API_URL=${MAIN_SERVER_API_URL}
      - PORT=${MAIN_SERVER_PORT}
      - DATABASE_URL=${MAIN_SERVER_DATABASE_URL}
      - COOKIE_DOMAIN=${MAIN_SERVER_COOKIE_DOMAIN}
      - FRONTEND_URL=${MAIN_SERVER_FRONTEND_URL}
      - DEV_MODE=${MAIN_SERVER_DEV_MODE}
      - GOOGLE_CLIENT_ID=${MAIN_SERVER_GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${MAIN_SERVER_GOOGLE_CLIENT_SECRET}
      - JWT_SECRET=${MAIN_SERVER_JWT_SECRET}
      - JWT_REFRESH_SECRET=${MAIN_SERVER_JWT_REFRESH_SECRET}
      - S3_ACCESS_KEY_ID=${MAIN_SERVER_S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${MAIN_SERVER_S3_SECRET_ACCESS_KEY}
      - S3_USE_SSL=${MAIN_SERVER_S3_USE_SSL}
      - S3_BUCKET=${MAIN_SERVER_S3_BUCKET}
      - S3_ENDPOINT=${MAIN_SERVER_S3_ENDPOINT}
      - S3_FRONTEND_URL=${MAIN_SERVER_S3_FRONTEND_URL}
    depends_on:
      db:
        condition: service_healthy
  config-server:
    image: cskulab/config-server:sha-98d3ea3
    environment:
      - MONGO_URI=${CONFIG_SERVER_MONGO_URI:-mongodb://config_server:config_password@mongo:27017/config_server}
      - PORT=${CONFIG_SERVER_PORT:-8081}
      - DATABASE_NAME=${MONGO_CONFIG_DB}
    ports:
      - "8081:8081"
    depends_on:
      mongo:
        condition: service_healthy
  task-server:
    image: cskulab/task-server:sha-2256055
    environment:
      - MONGO_URI=${TASK_SERVER_MONGO_URI:-mongodb://task_server:task_password@mongo:27017/task_server}
      - PORT=${TASK_SERVER_PORT:-8082}
      - DATABASE_NAME=${MONGO_TASK_DB}
    ports:
      - "8082:8082"
    depends_on:
      mongo:
        condition: service_healthy
  go-grader-master:
    image: cskulab/go-grader-master:sha-87283c1
    environment:
      - DATABASE_URL=${GO_GRADER_DATABASE_URL}
      - RBMQ_SERVER_URL=${GO_GRADER_RBMQ_SERVER_URL}
      - PORT=${GO_GRADER_PORT}
    ports:
      - "8083:8083"
    depends_on:
      rabbitmq:
        condition: service_healthy
  go-grader-worker:
    image: cskulab/go-grader-worker:sha-87283c1
    environment:
      - ENV=docker
      - CONFIG_SERVER_URL=${GO_GRADER_CONFIG_SERVER_URL}
      - TASK_SERVER_URL=${GO_GRADER_TASK_SERVER_URL}
      - RBMQ_SERVER_URL=${GO_GRADER_RBMQ_SERVER_URL}
    depends_on:
      rabbitmq:
        condition: service_healthy

  #--- infrastructures---

  db:
    image: postgres:18
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_MULTIPLE_DATABASES
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql # Persist data
      - ./setup_scripts/postgres/:/setup_scripts/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  s3:
    image: quay.io/minio/minio
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: ["server", "/data", "--console-address", ":9001"]
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  rabbitmq:
    image: rabbitmq:4.0-management
    hostname: queue
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  mongo:
    image: mongo:8-noble
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-password}
      - MONGO_CONFIG_USERNAME=${MONGO_CONFIG_USERNAME:-config_server}
      - MONGO_CONFIG_PASSWORD=${MONGO_CONFIG_PASSWORD:-config_password}
      - MONGO_TASK_USERNAME=${MONGO_TASK_USERNAME:-task_server}
      - MONGO_TASK_PASSWORD=${MONGO_TASK_PASSWORD:-task_password}
      - MONGO_CONFIG_DB=${MONGO_CONFIG_DB:-config_server}
      - MONGO_TASK_DB=${MONGO_TASK_DB:-task_server}
    volumes:
      - mongo_data:/data/db
      - ./setup_scripts/mongo:/setup_scripts/
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "mongodb://localhost:27017/admin",
          "--eval",
          "db.runCommand({ ping: 1 })",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  mongo-express:
    image: mongo-express
    ports:
      - "27018:8081"
    environment:
      - ME_CONFIG_MONGODB_URL

volumes:
  postgres_data:
  rabbitmq_data:
  mongo_data:
  minio_data:
